/// <reference lib="webworker" />

import { precacheAndRoute, cleanupOutdatedCaches } from 'workbox-precaching'
import { openDB, deleteDB } from 'idb'
import {
  type GymLibreDB,
  type GymLibreDatabase,
  type Exercise,
} from '@/types/db'

declare let self: ServiceWorkerGlobalScope

// Clean up old caches
cleanupOutdatedCaches()

// Handle skip waiting message
self.addEventListener('message', (event) => {
  if (event.data && event.data.type === 'SKIP_WAITING') {
    self.skipWaiting()
  }
})

// Initialize IndexedDB
async function initDB() {
  let db: GymLibreDatabase | undefined
  try {
    // Delete existing database first just to keep versions number at one during initial dev
    await deleteDB('gym-libre-db')
    console.log('Deleted existing database')

    db = await openDB<GymLibreDB>('gym-libre-db', 1, {
      upgrade(db, oldVersion) {
        console.log('Upgrade', oldVersion)
        switch (oldVersion) {
          case 0:
            console.log('Creating new database')
          // eslint-disable-next-line no-fallthrough
          case 1:
            console.log('Creating new exercises store')
            db.createObjectStore('exercises', {
              keyPath: 'id',
              autoIncrement: true,
            })
        }
      },
      blocked() {
        console.log('Database blocked')
      },
      blocking() {
        console.log('Database blocking')
      },
      terminated() {
        console.log('Database terminated')
      },
    })

    console.log('Version:', db.version)

    // Clear existing objects and add sample exercises
    try {
      const tx = db.transaction('exercises', 'readwrite')
      const store = tx.objectStore('exercises')

      // Delete all existing objects
      const keys = await store.getAllKeys()
      await Promise.all(keys.map((key) => store.delete(key)))
      console.log('Existing objects cleared')

      const exercises: Exercise[] = [
        {
          name: 'Bench Press',
          sets: [
            { set: 1, kg: 50, target: '3', reps: 3 },
            { set: 2, kg: 50, target: '3', reps: 3 },
            { set: 3, kg: 50, target: '3', reps: 3 },
            { set: 4, kg: 50, target: '3', reps: 3 },
            { set: 5, kg: 50, target: '3+', reps: 3 },
          ],
          date: new Date().toISOString().split('T')[0],
        },
        {
          name: 'Squat',
          sets: [
            { set: 1, kg: 80, target: '10', reps: 0 },
            { set: 2, kg: 80, target: '10', reps: 0 },
            { set: 3, kg: 80, target: '10', reps: 0 },
          ],
          date: new Date().toISOString().split('T')[0],
        },
        {
          name: 'Lat Pulldown',
          sets: [
            { set: 1, kg: 45, target: '15', reps: 0 },
            { set: 2, kg: 45, target: '15', reps: 0 },
            { set: 3, kg: 45, target: '15+', reps: 0 },
          ],
          date: new Date().toISOString().split('T')[0],
        },
      ]

      for (const exercise of exercises) {
        await store.add(exercise)
      }
      await tx.done
      console.log('Sample exercises added to database')
    } catch (txError) {
      console.error('Transaction error:', txError)
    }

    console.log('Database initialized in service worker')
  } catch (error) {
    console.error('Failed to initialize database in service worker:', error)
  } finally {
    if (db) {
      db.close()
    }
  }
}

// Initialize database during installation
self.addEventListener('install', (event) => {
  event.waitUntil(initDB())
})

// Precache all assets generated by vite
precacheAndRoute(self.__WB_MANIFEST)
